const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseTickets(text){
 const lines=text.replace(/<https?:\/\/[^|>]+\|([^>]+)>/g,'$1').replace(/\[([^\]]+)\]\(https?:\/\/[^)]+\)/g,'$1').split(/\r?\n/);const tickets=[];let current=null;
 const meta=/^(?:status\s*:|type\s*:|assignee\s*:|priority\s*:|Jira\b|.*created a \[System\]|Service request$|Today$|Yesterday$|\d{1,2}:\d{2}\s*[AP]M|[✓✅👀]|\d+$)/i;
 for(let line of lines){line=line.trim();if(!line){current=null;continue;} const matches=[...line.matchAll(/\bSTNHD-\d+\b/gi)];if(matches.length){for(let i=0;i<matches.length;i++){const m=matches[i];const id=m[0].toUpperCase();let title=line.slice(m.index+m[0].length,matches[i+1]?.index).replace(/^[\s|:\-–—>*]+/,'').replace(/\s+(?:Status|Assignee|Priority):.*$/i,'').trim();current={id,title};tickets.push(current);}}else if(meta.test(line)){current=null;}else if(current&&!/^https?:\/\//i.test(line)){current.title+=(current.title&&!/[A-Za-z0-9]-$/.test(current.title)?' ':'')+line;}}
 const unique=new Map();for(const t of tickets){if(!unique.has(t.id)||(!unique.get(t.id).title&&t.title))unique.set(t.id,t);}return [...unique.values()];
}
let plain='',rich='';
function update(){$('email').value=$('incoming').selectedOptions[0]?.dataset.email||'';const val=id=>$(id).value.trim();const tickets=parseTickets(val('slack'));$('ticket-count').textContent=`${tickets.length} ticket${tickets.length===1?'':'s'}`;
 $('extraction').innerHTML=tickets.map(t=>`<div class="ticket-row"><strong>${escapeHTML(t.id)}</strong><span>${escapeHTML(t.title||'No title found — add a description above.')}</span></div>`).join('')||(val('slack')?'<div class="parse-warning">No STNHD ticket IDs found. Include an ID such as STNHD-98181.</div>':'');
 const outgoing=val('outgoing')||'Not specified';const incoming=val('incoming')||'Not specified';const queue=val('queue')||'Not confirmed';const reassignment=val('reassignment')||'Not confirmed';const routing=$('routing').checked?'Yes':'Not verified';
 plain=`End of Shift Handoff Checklist\n\nOutgoing analyst: ${outgoing}\nSupport queue: ${queue}\nTicket reassignment: ${reassignment}\n\nTICKETS CREATED\n${tickets.length?tickets.map((t,i)=>`${i+1}. ${t.id} | ${t.title||'Description not provided'}`).join('\n'):'No tickets added.'}\n${val('notes')?'\nSHIFT NOTES\n'+val('notes')+'\n':''}\nNext Analyst on Shift\nName: ${incoming}\nEmail: ${val('email')||'Not provided'}\nPhone: ${val('phone')||'Not provided'}\n\nCALL ROUTING\nSupport number: ${val('support')||'Not provided'}\nOption: ${val('option')||'Not provided'}\nVerified and working: ${routing}`;
 rich=`<p><strong>Outgoing analyst:</strong> ${escapeHTML(outgoing)}</p><p><strong>Support queue:</strong> ${escapeHTML(queue)}</p><p><strong>Ticket reassignment:</strong> ${escapeHTML(reassignment)}</p><h4>Tickets created · ${tickets.length}</h4>${tickets.length?'<ul>'+tickets.map(t=>`<li><strong>${escapeHTML(t.id)}</strong> | ${escapeHTML(t.title||'Description not provided')}</li>`).join('')+'</ul>':'<p class="muted">No tickets added.</p>'}${val('notes')?`<h4>Shift notes</h4><p>${escapeHTML(val('notes')).replace(/\n/g,'<br>')}</p>`:''}<h4 style="font-weight:700"><strong>Next Analyst on Shift</strong></h4><p><strong>Name:</strong> ${escapeHTML(incoming)}<br><strong>Email:</strong> ${escapeHTML(val('email')||'Not provided')}<br><strong>Phone:</strong> ${escapeHTML(val('phone')||'Not provided')}</p><h4>Call routing</h4><p>Support: ${escapeHTML(val('support')||'Not provided')} · Option ${escapeHTML(val('option')||'Not provided')}<br><strong>Verified and working:</strong> ${routing}</p>`;
 $('document-body').innerHTML=rich;$('raw').textContent=plain;
 const missing=[];if(!val('outgoing')||!val('incoming'))missing.push('analyst names');if(!val('queue')||!val('reassignment'))missing.push('queue and reassignment status');if(!$('routing').checked)missing.push('routing verification');if(!$('email').checkValidity())missing.push('a valid email');if(!$('support').value.trim()||!$('option').value.trim())missing.push('support routing details');
 const pending=val('queue')==='Open tickets remain'||val('reassignment')==='Reassignment pending';$('readiness').textContent=missing.length?'Still to confirm: '+missing.join(', ')+'.':pending?'Checks recorded. Include any outstanding work in your shift notes.':'All handoff checks recorded. Review and share when ready.';$('readiness').classList.toggle('ready',!missing.length&&!pending);
}
$('handoff-form').addEventListener('input',update);$('handoff-form').addEventListener('change',update);$('handoff-form').addEventListener('submit',e=>e.preventDefault());
function tab(raw){$('raw').hidden=!raw;$('document').hidden=raw;['document-tab','text-tab'].forEach((id,i)=>{const active=raw===Boolean(i);$(id).classList.toggle('active',active);$(id).setAttribute('aria-selected',String(active));$(id).tabIndex=active?0:-1;});}
$('document-tab').onclick=()=>tab(false);$('text-tab').onclick=()=>tab(true);document.querySelector('.tabs').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const raw=$('text-tab').getAttribute('aria-selected')!=='true';tab(raw);$(raw?'text-tab':'document-tab').focus();}});
let timer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
$('copy').onclick=async()=>{try{if(navigator.clipboard?.write&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob(['<h2 style="font-weight:700"><strong>End of Shift Handoff Checklist</strong></h2>'+rich],{type:'text/html'}),'text/plain':new Blob([plain],{type:'text/plain'})})]);}else{await navigator.clipboard.writeText(plain);}toast('Handoff copied. Ready to paste.');}catch{try{await navigator.clipboard.writeText(plain);toast('Handoff copied as plain text.');}catch{tab(true);const range=document.createRange();range.selectNodeContents($('raw'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('Select and copy the handoff text, or use Download.');}}};
$('download').onclick=()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([plain],{type:'text/plain;charset=utf-8'}));a.href=url;a.download='STN-shift-handoff.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Handoff downloaded.');};
$('reset').onclick=()=>{if(confirm('Clear this handoff and start again?')){$('handoff-form').reset();tab(false);update();toast('Handoff reset.');}};
$('sample').onclick=()=>{if($('slack').value.trim()&&!confirm('Replace the current ticket messages with the example?'))return;$('slack').value=`Jira APP 6:36 AM\nSTN Portal created a [System]\nService request\nSTNHD-98180 SIEM Alert: Delivery\n& Attack Data Exfiltration\nStatus: Waiting for support\nType: [System] Service request\nAssignee: Unassigned Priority: Medium\n\nJira APP 6:52 AM\nMuhammad Talha created a [System]\nService request\nSTNHD-98181 High Severity Alert –\nLow Disk Space on FCTI-sv7-\nVVBalancer\nStatus: Waiting for support\nAssignee: Unassigned Priority: Medium\n\nSTN Portal created a [System]\nService request\nSTNHD-98182 SIEM Alert:\nEnvironmental Awareness\nAuthorization Bypass\nStatus: Waiting for support` ;update();toast('Example loaded from your screenshot. Review before sharing.');};
update();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_shift_handoff',description:'Read the current handoff draft and extracted tickets. Does not send or publish it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return {draft:plain,tickets:parseTickets($('slack').value),checks:$('readiness').textContent};}});register({name:'stage_slack_tickets',description:'Replace pasted Slack messages in the handoff draft and extract tickets. Does not send the handoff.',inputSchema:{type:'object',properties:{messages:{type:'string'}},required:['messages'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.messages!=='string'||Object.keys(input).some(k=>k!=='messages'))throw new Error('Provide a messages string.');$('slack').value=input.messages;update();return {tickets:parseTickets(input.messages)};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
